routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::resource('petroils', 'PetroilController');

Route::resource('accounts', 'AccountController');

Route::resource('deliveries', 'DeliveryController');

Route::resource('drums', 'DrumController');

Route::resource('orders', 'OrderController');

Route::resource('services', 'ServiceController');

app/Service.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Service extends Model
{
    protected $fillable = [
        'position',
        'data',
        'time',
        'product',
        'quantity',
        'vender'       
    ];
}

app/Http/Controllers/ServiceController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Service;
use Log;

class ServiceController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        Log::info('Service index');

        $services = Service::all();

        return view('services.index', compact('services'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        Log::info('Service create');

        return view('services.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        Log::info('Service store');

        $request->validate([
            'position'=>'required',
            'data'=>'required',
            'time'=>'required',
            'product'=>'required',
            'quantity'=>'required',
            'vender'=>'required'
        ]);

        $service = new Service([
            'position' => $request->get('position'),
            'data' => $request->get('data'),
            'time' => $request->get('time'),
            'product' => $request->get('product'),
            'quantity' => $request->get('quantity'),
            'vender' => $request->get('vender')
        ]);
        $service->save();
        return redirect('/services')->with('success', 'Service saved!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        Log::info('Service edit');

        $service = Service::find($id);
        return view('services.edit', compact('service'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'position'=>'required',
            'data'=>'required',
            'time'=>'required',
            'product'=>'required',
            'quantity'=>'required',
            'vender'=>'required'
        ]);

        $service = Service::find($id);
        $service->position =  $request->get('position');
        $service->data = $request->get('data');
        $service->time = $request->get('time');
        $service->product = $request->get('product');
        $service->quantity = $request->get('quantity');
        $service->vender = $request->get('vender');
        $service->save();

        return redirect('/services')->with('success', 'Service updated!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Log::info('Service destroy');

        $service = Service::find($id);
        $service->delete();

        return redirect('/services')->with('success', 'Service deleted!');
    }
}

resources/views/services/create.blade.php
@extends('base')

@section('main')
<div class="row">
 <div class="col-sm-8 offset-sm-2">
    <h1 class="display-3">Add a service</h1>
  <div>
    @if ($errors->any())
      <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
            @endforeach
        </ul>
      </div><br />
    @endif
      <form method="post" action="{{ route('services.store') }}">
          @csrf
          <div class="form-group">    
              <label for="position">Position:</label>
              <input type="string" class="form-control" name="position"/>
          </div>

          <div class="form-group">
              <label for="data">Data:</label>
              <input type="date" class="form-control" name="data"/>
          </div>

          <div class="form-group">
              <label for="time">Time:</label>
              <input type="time" class="form-control" name="time"/>
          </div>
          <div class="form-group">
              <label for="product">Product:</label>
              <input type="string" class="form-control" name="product"/>
          </div>
          <div class="form-group">
              <label for="quantity">Quantity:</label>
              <input type="integer" class="form-control" name="quantity"/>
          </div>
          <div class="form-group">
              <label for="vender">Vender:</label>
              <input type="string" class="form-control" name="vender"/>
          </div>                         
          <button type="submit" class="btn btn-primary-outline">Add vender</button>
      </form>
  </div>
</div>
</div>
@endsection

resources/views/services/edit.blade.php
@extends('base') 
@section('main')
<div class="row">
    <div class="col-sm-8 offset-sm-2">
        <h1 class="display-3">Update a service</h1>

        @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
        <br /> 
        @endif
        <form method="post" action="{{ route('services.update', $service->id) }}">
            @method('PATCH') 
            @csrf
            <div class="form-group">

                <label for="position">Position:</label>
                <input type="string" class="form-control" name="position" value={{ $service->position }} />
            </div>

            <div class="form-group">
                <label for="data">Data:</label>
                <input type="date" class="form-control" name="data" value={{ $service->data }} />
            </div>

            <div class="form-group">
                <label for="time">Time:</label>
                <input type="time" class="form-control" name="time" value={{ $service->time }} />
            </div>
            <div class="form-group">
                <label for="product">Product:</label>
                <input type="string" class="form-control" name="product" value={{ $service->product }} />
            </div>
            <div class="form-group">
                <label for="quantity">Quantity:</label>
                <input type="integer" class="form-control" name="quantity" value={{ $service->quantity }} />
            </div>
            <div class="form-group">
                <label for="vender">Vender:</label>
                <input type="string" class="form-control" name="vender" value={{ $service->vender }} />
            </div>
            <button type="submit" class="btn btn-primary">Update</button>
        </form>
    </div>
</div>
@endsection

resources/views/services/index.blade.php
@extends('base')

@section('main')
<div class="row">
<div class="col-sm-12">
    <h1 class="display-3">Services</h1>    
  <table class="table table-striped">
  <div>
    <a style="margin: 19px;" href="{{ route('services.create')}}" class="btn btn-primary">New service</a>
    </div>  
    <thead>
        <tr>
          <td>ID</td>
          <td>Position</td>
          <td>Data</td>
          <td>Time</td>
          <td>Product</td>
          <td>Quantity</td>
          <td>Vender</td>
          <td colspan = 2>Actions</td>
        </tr>
    </thead>
    <tbody>
        @foreach($services as $service)
        <tr>
            <td>{{$service->id}}</td>
            <td>{{$service->position}}</td>
            <td>{{$service->data}}</td>
            <td>{{$service->time}}</td>
            <td>{{$service->product}}</td>
            <td>{{$service->quantity}}</td>
            <td>{{$service->vender}}</td>
            <td>
                <a href="{{ route('services.edit',$service->id)}}" class="btn btn-primary">Edit</a>
            </td>
            <td>
                <form action="{{ route('services.destroy', $service->id)}}" method="post">
                  @csrf
                  @method('DELETE')
                  <button class="btn btn-danger" type="submit">Delete</button>
                </form>
            </td>
        </tr>
        @endforeach
    </tbody>
  </table>
<div>
<div class="col-sm-12">

  @if(session()->get('success'))
    <div class="alert alert-success">
      {{ session()->get('success') }}  
    </div>
  @endif
</div>
</div>
@endsection