routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::resource('petroils', 'PetroilController');

Route::resource('accounts', 'AccountController');

Route::resource('deliveries', 'DeliveryController');

Route::resource('drums', 'DrumController');

Route::resource('orders', 'OrderController');

Route::resource('services', 'ServiceController');

app/Drum.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Drum extends Model
{
    protected $fillable = [
        'dimesion',
        'max_liter',
        'position'     
    ];
    
    //orders
    public function orders(){

        return $this->belongsTo(Order::class);
        
        } 
}

app/Http/Controllers/DrumController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Drum;
use App\Order;
use Log;

class DrumController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        Log::info('Drum index');

        $drums = Drum::all();
        return view('drums.index', compact('drums'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        Log::info('Drum create');

        //order
        $drums = Drum::find(3)->orders;
        Log::info($drums);
        return view('drums.create', compact('orders'));

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        Log::info('Drum store');

        /*$request->validate([
            'dimension'=>'required',
            'max_liter'=>'required',
            'position'=>'required'
        ]);
*/
        $drum = new Drum([
            'dimension' => $request->get('dimension'),
            'max_liter' => $request->get('max_liter'),
            'position' => $request->get('position')
        ]);
        $drum->save();
        return redirect('/drums')->with('success', 'Drum saved!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        Log::info('Drum edit');
        
        $drum = Drum::find($id);
        return view('drums.edit', compact('drum')); 
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        Log::info('Drum update');

        $request->validate([
            'dimension'=>'required',
            'max_liter'=>'required',
            'position'=>'required'
        ]);

        $drum = Drum::find($id);
        $drum->dimension =  $request->get('dimension');
        $drum->max_liter = $request->get('max_liter');
        $drum->position = $request->get('position');
        $drum->save();

        return redirect('/drums')->with('success', 'Drum updated!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Log::info('Drum destroy');

        $drum = Drum::find($id);
        $drum->delete();

        return redirect('/drums')->with('success', 'Drum deleted!');
    }
}

resources/views/drums/create.blade.php
@extends('base')

@section('main')
<div class="row">
 <div class="col-sm-8 offset-sm-2">
    <h1 class="display-3">Add a drum</h1>
  <div>
    @if ($errors->any())
      <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
            @endforeach
        </ul>
      </div><br />
    @endif
      <form method="post" action="{{ route('drums.store') }}">
          @csrf
          <div class="form-group">    
              <label for="dimension">Dimension:</label>
              <input type="integer" class="form-control" name="dimension"/>
          </div>

          <div class="form-group">
              <label for="max_liter">Max liter:</label>
              <input type="integer" class="form-control" name="max_liter"/>
          </div>

          <div class="form-group">
              <label for="position">Position:</label>
              <input type="string" class="form-control" name="position"/>
          </div>

         <!-- <p> {{$drums ?? ''}} </p> -->
          <button type="submit" class="btn btn-primary-outline">Add drum</button>
      </form>
  </div>
</div>
</div>
@endsection

resources/views/drums/edit.blade.php
@extends('base') 
@section('main')
<div class="row">
    <div class="col-sm-8 offset-sm-2">
        <h1 class="display-3">Update a drum</h1>

        @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
        <br /> 
        @endif
        <form method="post" action="{{ route('drums.update', $drum->id) }}">
            @method('PATCH') 
            @csrf
            <div class="form-group">

                <label for="dimension">Dimension:</label>
                <input type="integer" class="form-control" name="dimension" value={{ $drum->dimension }} />
            </div>

            <div class="form-group">
                <label for="max_liter">Max liter:</label>
                <input type="integer" class="form-control" name="max_liter" value={{ $drum->max_liter }} />
            </div>

            <div class="form-group">
                <label for="position">Position:</label>
                <input type="string" class="form-control" name="position" value={{ $drum->position }} />
            </div>
            <button type="submit" class="btn btn-primary">Update</button>
        </form>
    </div>
</div>
@endsection

resources/views/drums/index.blade.php
@extends('base')

@section('main')
<div class="row">
<div class="col-sm-12">
    <h1 class="display-3">Drums</h1>    
  <table class="table table-striped">
  <div>
    <a style="margin: 19px;" href="{{ route('drums.create')}}" class="btn btn-primary">New drum</a>
    </div>  
    <thead>
        <tr>
          <td>ID</td>
          <td>Dimension</td>
          <td>Max liter</td>
          <td>Position</td>
          <td colspan = 2>Actions</td>
        </tr>
    </thead>
    <tbody>
        @foreach($drums as $drums)
        <tr>
            <td>{{$drums->id}}</td>
            <td>{{$drums->dimension}}</td>
            <td>{{$drums->max_liter}}</td>
            <td>{{$drums->position}}</td>
            <td>
                <a href="{{ route('drums.edit',$drums->id)}}" class="btn btn-primary">Edit</a>
            </td>
            <td>
                <form action="{{ route('drums.destroy', $drums->id)}}" method="post">
                  @csrf
                  @method('DELETE')
                  <button class="btn btn-danger" type="submit">Delete</button>
                </form>
            </td>
        </tr>
        @endforeach
    </tbody>
  </table>
<div>
<div class="col-sm-12">

  @if(session()->get('success'))
    <div class="alert alert-success">
      {{ session()->get('success') }}  
    </div>
  @endif
</div>
</div>
@endsection