routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::resource('petroils', 'PetroilController');

Route::resource('accounts', 'AccountController');

Route::resource('deliveries', 'DeliveryController');

Route::resource('drums', 'DrumController');

Route::resource('orders', 'OrderController');

Route::resource('services', 'ServiceController');

app/Petroil.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Petroil extends Model
{
    protected $fillable = [
        'type_oil',
        'percentage',
        'cost_hour'      
    ];
}

app/Http/Controllers/PetroilController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Petroil;
use Log;
class PetroilController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        Log::info('Petroil index');

        $petroils = Petroil::all();

        return view('petroils.index', compact('petroils'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        Log::info('Petroil Create');

        return view('petroils.create');

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        Log::info('Petroil Store');

        $request->validate([
            'type_oil'=>'required',
            'percentage'=>'required',
            'cost_hour'=>'required'
        ]);

        $petroil = new Petroil([
            'type_oil' => $request->get('type_oil'),
            'percentage' => $request->get('percentage'),
            'cost_hour' => $request->get('cost_hour')
        ]);
        $petroil->save();
        return redirect('/petroils')->with('success', 'Petroil saved!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        
        Log::info('Petroil edit');

        $petroil = Petroil::find($id);
        return view('petroils.edit', compact('petroil')); 
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {

        Log::info('Petroil update');

        $request->validate([
            'type_oil'=>'required',
            'percentage'=>'required',
            'cost_hour'=>'required'
        ]);

        $petroil = Petroil::find($id);
        $petroil->type_oil =  $request->get('type_oil');
        $petroil->percentage = $request->get('percentage');
        $petroil->cost_hour = $request->get('cost_hour');
        $petroil->save();

        return redirect('/petroils')->with('success', 'Petroil updated!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {

        Log::info('Petroil destroy');

        $petroil = Petroil::find($id);
        $petroil->delete();

        return redirect('/petroils')->with('success', 'Petroil deleted!');
    }
}

resources/views/petroils/create.blade.php
@extends('base')

@section('main')
<div class="row">
 <div class="col-sm-8 offset-sm-2">
    <h1 class="display-3">Add a petroil</h1>
  <div>
    @if ($errors->any())
      <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
            @endforeach
        </ul>
      </div><br />
    @endif
      <form method="post" action="{{ route('petroils.store') }}">
          @csrf
          <div class="form-group">    
              <label for="type_oil">Type of oil:</label>
              <input type="string" class="form-control" name="type_oil"/>
          </div>

          <div class="form-group">
              <label for="percentage">Percentage:</label>
              <input type="integer" class="form-control" name="percentage"/>
          </div>

          <div class="form-group">
              <label for="cost_hour">Cost por hour:</label>
              <input type="integer" class="form-control" name="cost_hour"/>
          </div>                 
          <button type="submit" class="btn btn-primary-outline">Add petroil</button>
      </form>
  </div>
</div>
</div>
@endsection

resources/views/petroils/edit.blade.php
@extends('base') 
@section('main')
<div class="row">
    <div class="col-sm-8 offset-sm-2">
        <h1 class="display-3">Update a petroil</h1>

        @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
        <br /> 
        @endif
        <form method="post" action="{{ route('petroils.update', $petroil->id) }}">
            @method('PATCH') 
            @csrf
            <div class="form-group">

                <label for="type_oil">Type of oil:</label>
                <input type="string" class="form-control" name="type_oil" value={{ $petroil->type_oil }} />
            </div>

            <div class="form-group">
                <label for="percentage">Percentage:</label>
                <input type="integer" class="form-control" name="percentage" value={{ $petroil->percentage }} />
            </div>

            <div class="form-group">
                <label for="cost_hour">Cost at hour:</label>
                <input type="integer" class="form-control" name="cost_hour" value={{ $petroil->cost_hour }} />
            </div>
            <button type="submit" class="btn btn-primary">Update</button>
        </form>
    </div>
</div>
@endsection

resources/views/petroils/index.blade.php
@extends('base')

@section('main')
<div class="row">
<div class="col-sm-12">
    <h1 class="display-3">Petroils</h1>    
  <table class="table table-striped">
  <div>
    <a style="margin: 19px;" href="{{ route('petroils.create')}}" class="btn btn-primary">New Petroil</a>
    </div>  
    <thead>
        <tr>
          <td>ID</td>
          <td>Type oil</td>
          <td>Percentage</td>
          <td>Cost for hour</td>
          <td colspan = 2>Actions</td>
        </tr>
    </thead>
    <tbody>
        @foreach($petroils as $petroil)
        <tr>
            <td>{{$petroil->id}}</td>
            <td>{{$petroil->type_oil}}</td>
            <td>{{$petroil->percentage}}</td>
            <td>{{$petroil->cost_hour}}</td>
            <td>
                <a href="{{ route('petroils.edit',$petroil->id)}}" class="btn btn-primary">Edit</a>
            </td>
            <td>
                <form action="{{ route('petroils.destroy', $petroil->id)}}" method="post">
                  @csrf
                  @method('DELETE')
                  <button class="btn btn-danger" type="submit">Delete</button>
                </form>
            </td>
        </tr>
        @endforeach
    </tbody>
  </table>
<div>
<div class="col-sm-12">

  @if(session()->get('success'))
    <div class="alert alert-success">
      {{ session()->get('success') }}  
    </div>
  @endif
</div>
</div>
@endsection