routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::resource('petroils', 'PetroilController');

Route::resource('accounts', 'AccountController');

Route::resource('deliveries', 'DeliveryController');

Route::resource('drums', 'DrumController');

Route::resource('orders', 'OrderController');

Route::resource('services', 'ServiceController');

app/Order.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\Account;
use App\Drum;

class Order extends Model
{
    protected $fillable = [
        'dimension',
        'type_oil',
        'oil_liter',
        'cost',
        'delivery'
    ];
    public function account(){

        return $this->belongsTo(Account::class);
        
        }
        //drum
    public function drums(){

        return $this->hasMany(Drum::class);
            
        }
}

app/Http/Controllers/OrderController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Order;
use Log;
use App\Account;

class OrderController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        Log::info('Order index');

        $orders = Order::all();

        return view('orders.index', compact('orders'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        Log::info('Order create');
        //account
        $orders = Order::find(3)->account;
        Log::info($orders);
        return view('orders.create', compact('orders'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        Log::info('Order store');

        Log::info($request);
        $request->validate([
            'dimension'=>'required',
            'type_oil'=>'required',
            'oil_liter'=>'required',
            'cost'=>'required',
            'delivery'=>'required'
        ]);

        $order = new Order([
            'dimension' => $request->get('dimension'),
            'type_oil' => $request->get('type_oil'),
            'oil_liter' => $request->get('oil_liter'),
            'cost' => $request->get('cost'),
            'delivery'=>$request->get('delivery')
        ]);
        $orders = Order::find(1)->orders;

        $order->save();
        return redirect('/orders')->with('success', 'Order saved!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        Log::info('Order edit');

        $order = Order::find($id);
        return view('orders.edit', compact('order'));  
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        Log::info('Order update');

        $request->validate([
            'dimension'=>'required',
            'type_oil'=>'required',
            'oil_liter'=>'required',
            'cost'=>'required',
            'delivery'=>'required'
        ]);

        $order = Order::find($id);
        $order->dimension =  $request->get('dimension');
        $order->type_oil = $request->get('type_oil');
        $order->oil_liter = $request->get('oil_liter');
        $order->cost = $request->get('cost');
        $order->delivery = $request->get('delivery');
        $order->save();

        return redirect('/orders')->with('success', 'Order updated!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Log::info('Order destroy');

        $order = Order::find($id);
        $order->delete();

        return redirect('/orders')->with('success', 'Order deleted!');
    }
}

resources/views/orders/create.blade.php
@extends('base')

@section('main')
<div class="row">
 <div class="col-sm-8 offset-sm-2">
    <h1 class="display-3">Add a orders</h1>
  <div>
    @if ($errors->any())
      <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
            @endforeach
        </ul>
      </div><br />
    @endif
      <form method="post" action="{{ route('orders.store') }}">
          @csrf
          <div class="form-group">    
              <label for="dimension">Dimension:</label>
              <input type="integer" class="form-control" name="dimension"/>
          </div>

          <div class="form-group">
              <label for="type_oil">Type of oil:</label>
              <input type="string" class="form-control" name="type_oil"/>
          </div>

          <div class="form-group">
              <label for="oil_liter">Oil liter:</label>
              <input type="integer" class="form-control" name="oil_liter"/>
          </div>
          <div class="form-group">
              <label for="cost">Cost:</label>
              <input type="integer" class="form-control" name="cost"/>
          </div>
          <div class="form-group">
              <label for="delivery">Delivery:</label>
              <select name="delivery">
              <option value="true">Active</option> 
              <option value="false">Not Active</option>
              </select>
            <p> {{$orders}} </p>
          </div>
          <button type="submit" class="btn btn-primary-outline">Add contact</button>
      </form>
  </div>
</div>
</div>
@endsection

resources/views/orders/edit.blade.php
@extends('base') 
@section('main')
<div class="row">
    <div class="col-sm-8 offset-sm-2">
        <h1 class="display-3">Update a order</h1>

        @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
        <br /> 
        @endif
        <form method="post" action="{{ route('orders.update', $order->id) }}">
            @method('PATCH') 
            @csrf
            <div class="form-group">

                <label for="dimension">Dimension:</label>
                <input type="integer" class="form-control" name="dimension" value={{ $order->dimension }} />
            </div>

            <div class="form-group">
                <label for="type_oil">Type of oil:</label>
                <input type="string" class="form-control" name="type_oil" value={{ $order->type_oil }} />
            </div>

            <div class="form-group">
                <label for="oil_liter">Oil liter:</label>
                <input type="integer" class="form-control" name="oil_liter" value={{ $order->oil_liter }} />
            </div>
            <div class="form-group">
                <label for="cost">Cost:</label>
                <input type="integer" class="form-control" name="cost" value={{ $order->cost }} />
            </div>
            <div class="form-group">
                <label for="delivery">Delivery:</label>
                <input type="boolean" class="form-control" name="delivery" value={{ $order->delivery }} />
            </div>
            <button type="submit" class="btn btn-primary">Update</button>
        </form>
    </div>
</div>
@endsection

resources/views/orders/index.blade.php
@extends('base')

@section('main')
<div class="row">
<div class="col-sm-12">
    <h1 class="display-3">Orders</h1>    
  <table class="table table-striped">
  <div>
    <a style="margin: 19px;" href="{{ route('orders.create')}}" class="btn btn-primary">New order</a>
    </div> 
    <thead>
        <tr>
          <td>ID</td>
          <td>Dimension</td>
          <td>Type of oil</td>
          <td>Oil liter</td>
          <td>Cost</td>
          <td>Delivery</td>
          <td colspan = 2>Actions</td>
        </tr>
    </thead>
    <tbody>
        @foreach($orders as $order)
        <tr>
            <td>{{$order->id}}</td>
            <td>{{$order->dimension}}</td>
            <td>{{$order->type_oil}}</td>
            <td>{{$order->oil_liter}}</td>
            <td>{{$order->cost}}</td>
            <td>{{$order->delivery}}</td>
            <td>
                <a href="{{ route('orders.edit',$order->id)}}" class="btn btn-primary">Edit</a>
            </td>
            <td>
                <form action="{{ route('orders.destroy', $order->id)}}" method="post">
                  @csrf
                  @method('DELETE')
                  <button class="btn btn-danger" type="submit">Delete</button>
                </form>
            </td>
        </tr>
        @endforeach
    </tbody>
  </table>
<div>
<div class="col-sm-12">

  @if(session()->get('success'))
    <div class="alert alert-success">
      {{ session()->get('success') }}  
    </div>
  @endif
</div>
</div>
@endsection